export default{
        permissionUser:[],
        permissAllow:{
                //云支付申请跟进总表
                //查看
                "CloudPayInquiry.CloudApplicationFormSummaryStatement.Inquiry":false,        
                //关闭
                "CloudPayInquiry.CloudApplicationFormSummaryStatement.Close":false,
                //修改备注
                "CloudPayInquiry.CloudApplicationFormSummaryStatement.ModifyRemark":false,
                //品牌认证跟进总表
                //查看
                "CloudPayInquiry.BrandCertificationApplicationFormSummaryStatement.Inquiry":false,
                //关闭
                "CloudPayInquiry.BrandCertificationApplicationFormSummaryStatement.Close":false,
                //品牌总表
                //查看
                "CloudPayInquiry.ProjectBrandSummaryStatement.Inquiry":false,
                //云支付收款账号申请跟进总表
                //查看
                "CloudPayInquiry.ReceivableAccountApplicationFormSummaryStatement.Inquiry":false,
                //关闭
                "CloudPayInquiry.ReceivableAccountApplicationFormSummaryStatement.Close":false,
                //新建申请单
                "CloudPay.CloudApplicationForm.Create" :false,
                //受理&完成申请单
                "CloudPay.CloudApplicationForm.AcceptAndFinish":false,
                //申请品牌认证
                "CloudPay.BrandCertificationApplicationForm.Create":false,
                //提交认证资料
                "CloudPay.BrandCertificationApplicationForm.Upload":false,
                //品牌认证
                "CloudPay.BrandCertificationApplicationForm.Verify":false,
                //开通云单据
                "CloudPay.BrandCertificationApplicationForm.OpenOrder":false,
                //开通云支付
                "CloudPay.BrandCertificationApplicationForm.OpenPay":false,
                //申请云支付收款账号
                "CloudPay.ApplicationFormFollowUp.Create":false,
                //安排培训机构
                "CloudPay.ApplicationFormFollowUp.ArrangeTrainingInstitution":false,
                //人员
                "SystemSetting.Users":false,
                //权限
                "SystemSetting.Permissions":false,
        }
}